#ifndef WLH_LWIPOPTS_H
#define WLH_LWIPOPTS_H

#define NO_SYS 0
#define SYS_LIGHTWEIGHT_PROT 1

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_ICMP 1
#define LWIP_RAW 1
#define LWIP_UDP 1
#define LWIP_TCP 0

#define LWIP_NETCONN 0
#define LWIP_SOCKET 0
#define LWIP_NETIF_API 0
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_STATS 0

#define MEM_ALIGNMENT 8
#define MEM_SIZE (64 * 1024)
#define MEMP_NUM_RAW_PCB 4
#define MEMP_NUM_UDP_PCB 8
#define MEMP_NUM_SYS_TIMEOUT 16
#define MEMP_NUM_TCPIP_MSG_API 8
#define MEMP_NUM_TCPIP_MSG_INPKT 32
#define PBUF_POOL_SIZE 32
#define PBUF_POOL_BUFSIZE 1600

#define TCPIP_THREAD_NAME "wlh-lwip"
#define TCPIP_THREAD_STACKSIZE (64 * 1024)
#define TCPIP_THREAD_PRIO 0
#define TCPIP_MBOX_SIZE 32
#define DEFAULT_UDP_RECVMBOX_SIZE 8
#define DEFAULT_RAW_RECVMBOX_SIZE 8

#define LWIP_CHKSUM_ALGORITHM 3
#define CHECKSUM_GEN_IP 1
#define CHECKSUM_GEN_UDP 1
#define CHECKSUM_GEN_ICMP 1
#define CHECKSUM_CHECK_IP 1
#define CHECKSUM_CHECK_UDP 1
#define CHECKSUM_CHECK_ICMP 1

#endif
